require 'rails-assets-angular-gettext'
require 'rails-assets-ng-grid'
require 'rails-assets-restangular'
require 'rails-assets-ngQuickDate'
require 'rails-assets-select2'
require 'rails-assets-angular-ui-select2'
require 'rails-assets-ng-flow'
require 'rails-assets-angular-ui-router'
